/** @format */

import type { Metadata } from "next";
import "@/style/globals.css";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
    title: "Safiullah",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> */}
                    {children}
                {/* </ThemeProvider> */}
            </body>
        </html>
    );
}
